server:
  port: 8088
  servlet:
    encoding:
      force: true  #解决抛出异常处理中文乱码问题

spring:
  datasource:
    url: jdbc:mysql://192.168.126.133:3306/tes_security_jwt?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  token\u914D\u7F6E
token:
  #  \u4EE4\u724C\u81EA\u5B9A\u4E49\u6807\u8BC6
  header: Authorization
  #  \u4EE4\u724C\u79D8\u94A5
  #	secret:  5eb4x7dpl  \u4EFB\u610F\u5B57\u7B26
  secret: 5eb4x7dpl
  #   \u4EE4\u724C\u6709\u6548\u671F\uFF08\u9ED8\u8BA430\u5206\u949F\uFF09
  expireTime: 3600000